services:
  - type: web
    name: sanad
    runtime: python
    repo: https://github.com/txglobalpro/Sanad
    branch: master
    plan: free
    autoDeploy: yes
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
